name: Flutter Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
         flutter-version: '2.8.1'

      - run: flutter pub get
      - run: flutter build apk

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Deploy APK to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: success()
        with:
          branch: gh-pages
          folder: app/build/outputs/apk/debug/
          token: ${{ secrets.GITHUB_TOKEN }}